packages = ["pokerkit"]

[files]
"./main.py" = "./main.py"
"./poker_core.py" = "./poker_core.py"
"./game_state.py" = "./game_state.py"
"./cards_html.py" = "./cards_html.py"
"./bot_backend.py" = "./bot_backend.py"
"./live_seat_metrics.py" = "./live_seat_metrics.py"
"./heuristics.py" = "./heuristics.py"
"./hand_eval.py" = "./hand_eval.py"
"./table_guests.py" = "./table_guests.py"
"./avatars.py" = "./avatars.py"
"./avatar_img/mahatma-gandhi.png" = "./avatar_img/mahatma-gandhi.png"
"./avatar_img/madonna.png" = "./avatar_img/madonna.png"
"./avatar_img/cleopatra.png" = "./avatar_img/cleopatra.png"
"./avatar_img/napoleon.png" = "./avatar_img/napoleon.png"
"./avatar_img/taylor-swift.png" = "./avatar_img/taylor-swift.png"
"./avatar_img/albert-einstein.png" = "./avatar_img/albert-einstein.png"
"./avatar_img/genghis-khan.png" = "./avatar_img/genghis-khan.png"
"./avatar_img/julius-caesar.png" = "./avatar_img/julius-caesar.png"
"./avatar_img/abraham-lincoln.png" = "./avatar_img/abraham-lincoln.png"
"./avatar_img/freddie-mercury.png" = "./avatar_img/freddie-mercury.png"
"./avatar_img/elvis-presley.png" = "./avatar_img/elvis-presley.png"
"./avatar_img/winston-churchill.png" = "./avatar_img/winston-churchill.png"
"./avatar_img/socrates.png" = "./avatar_img/socrates.png"
"./avatar_img/mr-bean.png" = "./avatar_img/mr-bean.png"
"./avatar_img/dr-bukowy.png" = "./avatar_img/dr-bukowy.png"
